# 📂 Project 1: The E-Commerce Sales Analysis
The Scenario: You have just been hired as a Junior Data Analyst for an electronics retail store. The manager hands you a messy dump of sales data from 2024. He asks: "How was our performance last year? What was our best month? What city buys the most electronics?"  

**The Problem**: The data is garbage.
- The dates are strings.
- The prices are stored as text.
- The addresses are all combined in one long string.
- There are empty rows (NaN).

**Your Goal**: Take this raw data, clean it, analyse it, and answer 3 business questions.

In [1]:
import pandas as pd
import numpy as np

In [3]:
# Generating a realistic messy dataset
data = {
    'Order ID': ['176558', '176559', np.nan, '176560', '176561', '176562', '176558'], # Note duplicate ID at end
    'Product': ['USB-C Charging Cable', 'Bose SoundSport Headphones', np.nan, 'Google Phone', 'Wired Headphones', 'USB-C Charging Cable', 'USB-C Charging Cable'],
    'Quantity Ordered': ['2', '1', np.nan, '1', '1', '1', '2'], # Stored as Strings!
    'Price Each': ['11.95', '99.99', np.nan, '600', '11.99', '11.95', '11.95'], # Stored as Strings!
    'Order Date': ['04/19/2024 08:46', '04/07/2024 22:30', np.nan, '04/12/2024 14:38', '04/30/2024 09:27', '04/29/2024 13:03', '04/19/2024 08:46'],
    'Purchase Address': [
        '917 1st St, Dallas, TX 75001', 
        '682 Chestnut St, Boston, MA 02215', 
        np.nan, 
        '669 Spruce St, Los Angeles, CA 90001', 
        '333 8th St, Los Angeles, CA 90001', 
        '381 Wilson St, San Francisco, CA 94016',
        '917 1st St, Dallas, TX 75001'
    ]
}

In [4]:
df = pd.DataFrame(data)

In [5]:
df.shape

(7, 6)

In [6]:
df.dtypes

Order ID            object
Product             object
Quantity Ordered    object
Price Each          object
Order Date          object
Purchase Address    object
dtype: object

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   Order ID          6 non-null      object
 1   Product           6 non-null      object
 2   Quantity Ordered  6 non-null      object
 3   Price Each        6 non-null      object
 4   Order Date        6 non-null      object
 5   Purchase Address  6 non-null      object
dtypes: object(6)
memory usage: 468.0+ bytes


In [8]:
df.describe()

Order ID               Product Quantity Ordered Price Each  \
count         6                     6                6          6   
unique        5                     4                2          4   
top      176558  USB-C Charging Cable                1      11.95   
freq          2                     3                4          3   

              Order Date              Purchase Address  
count                  6                             6  
unique                 5                             5  
top     04/19/2024 08:46  917 1st St, Dallas, TX 75001  
freq                   2                             2

In [9]:
df

Order ID                     Product Quantity Ordered Price Each  \
0   176558        USB-C Charging Cable                2      11.95   
1   176559  Bose SoundSport Headphones                1      99.99   
2      NaN                         NaN              NaN        NaN   
3   176560                Google Phone                1        600   
4   176561            Wired Headphones                1      11.99   
5   176562        USB-C Charging Cable                1      11.95   
6   176558        USB-C Charging Cable                2      11.95   

         Order Date                        Purchase Address  
0  04/19/2024 08:46            917 1st St, Dallas, TX 75001  
1  04/07/2024 22:30       682 Chestnut St, Boston, MA 02215  
2               NaN                                     NaN  
3  04/12/2024 14:38    669 Spruce St, Los Angeles, CA 90001  
4  04/30/2024 09:27       333 8th St, Los Angeles, CA 90001  
5  04/29/2024 13:03  381 Wilson St, San Francisco, CA 94016  
6  04/19/2024 08:46            917 1st St, Dallas, TX 75001

# Phase 1: Data Cleaning  
📝 **Tasks**:
- Drop NaNs: Remove any rows that have missing values.
- Remove Duplicates: There are duplicate rows (check Order ID). Remove them.
- Fix Types:
    - Convert Quantity Ordered to an integer.
    - Convert Price Each to a float.\
    - Convert Order Date to a datetime object


In [10]:
# Detecting Missing Values
df.isnull().sum()

# Drop the missing data
df.dropna(inplace = True)

In [11]:
# Detecting Dulicate values
df.duplicated()

0    False
1    False
3    False
4    False
5    False
6     True
dtype: bool

In [12]:
df[df.duplicated()]

Order ID               Product Quantity Ordered Price Each  \
6   176558  USB-C Charging Cable                2      11.95   

         Order Date              Purchase Address  
6  04/19/2024 08:46  917 1st St, Dallas, TX 75001

In [13]:
# Drop duplicate value
df.drop_duplicates(inplace = True)

In [14]:
# Replace space from column names with _
df.columns = df.columns.str.replace(" ", '_')

# Converting quantity order data type to integer
df['Quantity_Ordered'] = pd.to_numeric(df['Quantity_Ordered'], errors = 'coerce')


# Converting price data type to float
df['Price_Each'] = pd.to_numeric(df['Price_Each'], errors = 'coerce')

# Converting ordere date data type to datetime
df['Order_Date'] = pd.to_datetime(df['Order_Date'], format = 'mixed', errors = 'coerce')

In [15]:
df.dtypes

Order_ID                    object
Product                     object
Quantity_Ordered             int64
Price_Each                 float64
Order_Date          datetime64[ns]
Purchase_Address            object
dtype: object

# Phase 2: Feature Engineering (Creating New Tools)  

✅Now that the data is clean, we need to build the tools to answer the questions.  

**The Business Questions:**  
- What was the best month for sales? (We need a Month column).
- Which city sold the most product? (We need a City column).
- How much money did we make? (We need a Sales column).

**🎓Tasks**  
**Task 1:** Add a "Sales" Column We have Quantity_Ordered and Price_Each  
**Task 2:** Add a "Month" Column We have Order_Date as a datetime object (thanks to your cleaning)   
**Task 3:** Add a "City" Column (The Hard One) Look at the Purchase_Address column: "917 1st St, Dallas, TX 75001"  

In [16]:
df['Sales'] = df['Quantity_Ordered'] * df['Price_Each']

In [17]:
df

Order_ID                     Product  Quantity_Ordered  Price_Each  \
0   176558        USB-C Charging Cable                 2       11.95   
1   176559  Bose SoundSport Headphones                 1       99.99   
3   176560                Google Phone                 1      600.00   
4   176561            Wired Headphones                 1       11.99   
5   176562        USB-C Charging Cable                 1       11.95   

           Order_Date                        Purchase_Address   Sales  
0 2024-04-19 08:46:00            917 1st St, Dallas, TX 75001   23.90  
1 2024-04-07 22:30:00       682 Chestnut St, Boston, MA 02215   99.99  
3 2024-04-12 14:38:00    669 Spruce St, Los Angeles, CA 90001  600.00  
4 2024-04-30 09:27:00       333 8th St, Los Angeles, CA 90001   11.99  
5 2024-04-29 13:03:00  381 Wilson St, San Francisco, CA 94016   11.95

In [18]:
df['Month'] = df['Order_Date'].dt.month

In [29]:
df['City'] = df['Purchase_Address'].str.split(',').str[1].str.strip()

In [30]:
df

Order_ID                     Product  Quantity_Ordered  Price_Each  \
0   176558        USB-C Charging Cable                 2       11.95   
1   176559  Bose SoundSport Headphones                 1       99.99   
3   176560                Google Phone                 1      600.00   
4   176561            Wired Headphones                 1       11.99   
5   176562        USB-C Charging Cable                 1       11.95   

           Order_Date                        Purchase_Address   Sales  Month  \
0 2024-04-19 08:46:00            917 1st St, Dallas, TX 75001   23.90      4   
1 2024-04-07 22:30:00       682 Chestnut St, Boston, MA 02215   99.99      4   
3 2024-04-12 14:38:00    669 Spruce St, Los Angeles, CA 90001  600.00      4   
4 2024-04-30 09:27:00       333 8th St, Los Angeles, CA 90001   11.99      4   
5 2024-04-29 13:03:00  381 Wilson St, San Francisco, CA 94016   11.95      4   

            City  
0         Dallas  
1         Boston  
3    Los Angeles  
4    Los Angeles  
5  San Francisco

# Phase 3: The Analysis (Final Step)  
Now your data is pristine. It is time to impress the boss.

**Your Mission:** Write the code to answer these two questions using **GroupBy:**

- **Best Month:** Which month had the highest total Sales? (Sort the values so the winner is at the top).
- **Best City:** Which city generated the most revenue?

In [41]:
df.sort_values(by = 'Sales', inplace = True, ascending = False)

In [49]:
best_month = df.groupby('Month')['Sales'].sum()

In [52]:
best_month

Month
4    747.83
Name: Sales, dtype: float64

In [53]:
city = df.groupby('City')['Sales'].sum().sort_values(ascending = False)

In [58]:
best_city = city.iloc[[0]]

In [61]:
best_city

City
Los Angeles    611.99
Name: Sales, dtype: float64

In [62]:
df['Hour'] = df['Order_Date'].dt.hour

In [93]:
busy_hours = df.groupby('Hour')['Order_ID'].count()

In [94]:
# Let's see the peak times
print(busy_hours.sort_values(ascending=False))

Hour
8     1
9     1
13    1
14    1
22    1
Name: Order_ID, dtype: int64
